// Known-answer tests for Hyperliquid signing against vectors generated by
// the official hyperliquid-python-sdk (fixtures/generate_hl_vectors.py).
//
// Byte equality is asserted up to the EIP-712 digest. Signatures are
// validated by ecRecover instead: polybrainz signs with a Keccak-HMAC
// deterministic-k, eth_account with RFC 6979 (HMAC-SHA256) — both valid,
// never byte-identical. Recovering the Python signature over OUR digest
// additionally proves digest equivalence through independent plumbing.

import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:kute/constants/hyperliquid_constants.dart';
import 'package:kute/services/hyperliquid/hyperliquid_signing.dart';
import 'package:polybrainz_polymarket/polybrainz_polymarket.dart'
    show EthPrivateKey;
import 'package:web3dart/web3dart.dart'
    show MsgSignature, ecRecover, publicKeyToAddress;

import 'hyperliquid_test_actions.dart';

const _key =
    '0x0123456789012345678901234567890101234567890123456789012345678901';

/// The user-signed vectors were generated by the official Python SDK, which
/// hardcodes signatureChainId 0x66eee. Production now signs on Arbitrum
/// (0xa4b1, the documented value), so every SDK vector pins its chain
/// explicitly and still proves the signer against the reference.
const int _sdkVectorChainId = 0x66eee;

Uint8List _fromHex(String hexStr) {
  final clean = hexStr.replaceFirst('0x', '');
  return Uint8List.fromList([
    for (var i = 0; i < clean.length; i += 2)
      int.parse(clean.substring(i, i + 2), radix: 16),
  ]);
}

String _toHex(List<int> bytes) =>
    bytes.map((b) => b.toRadixString(16).padLeft(2, '0')).join();

String _recoverAddress(Uint8List digest, Map<String, dynamic> sig) {
  final pubKey = ecRecover(
    digest,
    MsgSignature(
      BigInt.parse((sig['r'] as String).substring(2), radix: 16),
      BigInt.parse((sig['s'] as String).substring(2), radix: 16),
      sig['v'] as int,
    ),
  );
  return '0x${_toHex(publicKeyToAddress(pubKey))}';
}

void main() {
  final vectors = jsonDecode(
          File('test/services/fixtures/hl_vectors.json').readAsStringSync())
      as Map<String, dynamic>;
  final signer = (vectors['signer'] as String).toLowerCase();
  final credentials = EthPrivateKey.fromHex(_key);
  final actions = buildHlTestActions();

  group('L1 actions', () {
    for (final raw in vectors['l1Actions'] as List) {
      final entry = raw as Map<String, dynamic>;
      final name = entry['name'] as String;
      final baseName = name
          .replaceFirst('_vault', '')
          .replaceFirst('_expires', '');
      final action = actions[baseName]!;

      test('$name — connectionId + digests + signatures', () async {
        final connectionId = actionHash(
          action: action,
          nonce: entry['nonce'] as int,
          vaultAddress: entry['vaultAddress'] as String?,
          expiresAfter: entry['expiresAfter'] as int?,
        );
        expect(_toHex(connectionId), entry['connectionIdHex']);

        for (final (isMainnet, net) in [(true, 'mainnet'), (false, 'testnet')]) {
          final digest =
              l1ActionDigest(connectionId: connectionId, isMainnet: isMainnet);
          expect(_toHex(digest), entry['digest_$net'],
              reason: '$net digest mismatch');

          // Python's signature recovers to the signer over OUR digest.
          final pySig = entry['pythonSig_$net'] as Map<String, dynamic>;
          expect(_recoverAddress(digest, pySig), signer);

          // Our signature over the same digest also recovers to the signer.
          final ourSig = await signL1Action(
            credentials: credentials,
            action: action,
            nonce: entry['nonce'] as int,
            vaultAddress: entry['vaultAddress'] as String?,
            expiresAfter: entry['expiresAfter'] as int?,
            isMainnet: isMainnet,
          );
          expect(_recoverAddress(digest, ourSig.toJson()), signer);
        }
      });
    }
  });

  group('user-signed actions', () {
    final fieldsByType = {
      'HyperliquidTransaction:Withdraw': withdrawSignTypes,
      'HyperliquidTransaction:UsdClassTransfer': usdClassTransferSignTypes,
      'HyperliquidTransaction:ApproveBuilderFee': approveBuilderFeeSignTypes,
    };
    for (final raw in vectors['userSignedActions'] as List) {
      final entry = raw as Map<String, dynamic>;
      test(entry['name'] as String, () async {
        final action =
            Map<String, dynamic>.from(entry['action'] as Map);
        final primaryType = entry['primaryType'] as String;
        final digest = userSignedActionDigest(
          primaryType: primaryType,
          fields: fieldsByType[primaryType]!,
          message: action,
          signatureChainId: _sdkVectorChainId,
        );
        expect(_toHex(digest), entry['digest']);
        expect(
            _recoverAddress(
                digest, entry['pythonSig'] as Map<String, dynamic>),
            signer);
      });
    }

    test('signUserSignedAction augments the action like the Python SDK', () async {
      final action = buildWithdraw3Action(
        destination: '0x5e9ee1089755c3435139848e47e6635505d5a13a',
        amount: '100.5',
        time: vectors['nonce'] as int,
      );
      final sig = await signUserSignedAction(
        credentials: credentials,
        action: action,
        fields: withdrawSignTypes,
        primaryType: withdrawPrimaryType,
        isMainnet: true,
        signatureChainId: _sdkVectorChainId,
      );
      expect(action['signatureChainId'], '0x66eee');
      expect(action['hyperliquidChain'], 'Mainnet');
      final expected = (vectors['userSignedActions'] as List).firstWhere(
          (e) => e['name'] == 'withdraw3_mainnet') as Map<String, dynamic>;
      final digest = _fromHex(expected['digest'] as String);
      expect(_recoverAddress(digest, sig.toJson()), signer);
    });

    // The default signatureChainId is Arbitrum (0xa4b1), the value the docs
    // define and every documented example uses. The SDK's 0x66eee (the
    // vectors above) changes only the EIP-712 domain and the POSTed hex
    // field — the struct hash is identical, so the SDK vectors still prove
    // the field encoding for the production chain.
    test('the default signatureChainId is 0xa4b1; 0x66eee changes only the '
        'domain and the hex field', () async {
      expect(HyperliquidConstants.signatureChainId, 42161);
      expect(HyperliquidConstants.signatureChainIdHex, '0xa4b1');
      Map<String, dynamic> build() => buildUsdClassTransferAction(
          amount: '10.5', toPerp: false, nonce: vectors['nonce'] as int);
      final production = build();
      final sdk = build();
      final productionSig = await signUserSignedAction(
        credentials: credentials,
        action: production,
        fields: usdClassTransferSignTypes,
        primaryType: usdClassTransferPrimaryType,
        isMainnet: true,
      );
      await signUserSignedAction(
        credentials: credentials,
        action: sdk,
        fields: usdClassTransferSignTypes,
        primaryType: usdClassTransferPrimaryType,
        isMainnet: true,
        signatureChainId: _sdkVectorChainId,
      );
      expect(production['signatureChainId'], '0xa4b1');
      expect(sdk['signatureChainId'], '0x66eee');
      expect(Map.of(sdk)..remove('signatureChainId'),
          Map.of(production)..remove('signatureChainId'));

      final productionHashes = userSignedActionHashes(
          primaryType: usdClassTransferPrimaryType,
          fields: usdClassTransferSignTypes,
          message: production);
      final explicit = userSignedActionHashes(
          primaryType: usdClassTransferPrimaryType,
          fields: usdClassTransferSignTypes,
          message: production,
          signatureChainId: 42161);
      final sdkHashes = userSignedActionHashes(
          primaryType: usdClassTransferPrimaryType,
          fields: usdClassTransferSignTypes,
          message: sdk,
          signatureChainId: _sdkVectorChainId);
      expect(_toHex(productionHashes.digest), _toHex(explicit.digest));
      expect(_toHex(sdkHashes.message), _toHex(productionHashes.message));
      expect(_toHex(sdkHashes.domain), isNot(_toHex(productionHashes.domain)));
      expect(_recoverAddress(productionHashes.digest, productionSig.toJson()),
          signer);
    });
  });

  test('HlSignature.toJson uses minimal 0x hex like Python to_hex', () {
    final sig = HlSignature(r: BigInt.parse('abc', radix: 16), s: BigInt.one, v: 27);
    expect(sig.toJson(), {'r': '0xabc', 's': '0x1', 'v': 27});
  });
}
