// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:kute/models/balance_model.dart';
import 'package:kute/models/swap_order_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(SwapOrderAdapter());
    registerAdapter(WalletBalanceAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(SwapOrderAdapter());
    registerAdapter(WalletBalanceAdapter());
  }
}
