// A real Gamma Exact Score event, trimmed to the keys the app reads:
// Tottenham Hotspur FC vs. Coventry City FC, read from
// gamma-api.polymarket.com/events?slug=epl-tot-cov-2026-10-19-exact-score
// on 2026-10-07. Titles, prices, quotes and last trades are Gamma's own;
// token ids are shortened. Most books there have no bid and one ask far
// above, which is why `outcomePrices` read ~37% for nearly every score.

Map<String, dynamic> exactScoreMarket(
        int i, String question, String title, String prices,
        {Object? bid, Object? ask, Object? spread, Object? last}) =>
    {
      'id': 'es$i',
      'question': question,
      'groupItemTitle': title,
      'conditionId': '0xes$i',
      'outcomes': '["Yes", "No"]',
      'outcomePrices': prices,
      'clobTokenIds': '["es${i}y", "es${i}n"]',
      'sportsMarketType': 'soccer_exact_score',
      if (bid != null) 'bestBid': bid,
      if (ask != null) 'bestAsk': ask,
      if (spread != null) 'spread': spread,
      if (last != null) 'lastTradePrice': last,
      'volumeNum': 0,
    };

/// The event as Gamma sends it.
Map<String, dynamic> exactScoreEventRaw() => {
      'id': '1140932',
      'slug': "epl-tot-cov-2026-10-19-exact-score",
      'title': "Tottenham Hotspur FC vs. Coventry City FC - Exact Score",
      'startTime': "2026-10-19T19:00:00Z",
      'gameId': 90114132,
      'tags': [
        {'slug': 'sports'},
        {'slug': 'soccer'}
      ],
      'teams': [
        {
          'name': "Tottenham Hotspur FC",
          'abbreviation': "tot",
          'ordering': "home"
        },
        {'name': "Coventry City FC", 'abbreviation': "cov", 'ordering': "away"},
      ],
      'markets': [
        exactScoreMarket(
            0,
            "Exact Score: Tottenham Hotspur FC 0 - 0 Coventry City FC?",
            "Tottenham Hotspur FC 0 - 0 Coventry City FC",
            '["0.34", "0.66"]',
            ask: 0.68,
            spread: 0.68),
        exactScoreMarket(
            1,
            "Exact Score: Tottenham Hotspur FC 0 - 1 Coventry City FC?",
            "Tottenham Hotspur FC 0 - 1 Coventry City FC",
            '["0.32", "0.68"]',
            ask: 0.64,
            spread: 0.64),
        exactScoreMarket(
            2,
            "Exact Score: Tottenham Hotspur FC 1 - 0 Coventry City FC?",
            "Tottenham Hotspur FC 1 - 0 Coventry City FC",
            '["0.09", "0.91"]',
            bid: 0.06,
            ask: 0.12,
            spread: 0.06),
        exactScoreMarket(
            3,
            "Exact Score: Tottenham Hotspur FC 0 - 2 Coventry City FC?",
            "Tottenham Hotspur FC 0 - 2 Coventry City FC",
            '["0.33", "0.67"]',
            ask: 0.66,
            spread: 0.66),
        exactScoreMarket(
            4,
            "Exact Score: Tottenham Hotspur FC 1 - 1 Coventry City FC?",
            "Tottenham Hotspur FC 1 - 1 Coventry City FC",
            '["0.09", "0.91"]',
            bid: 0.06,
            ask: 0.12,
            spread: 0.06),
        exactScoreMarket(
            5,
            "Exact Score: Tottenham Hotspur FC 2 - 0 Coventry City FC?",
            "Tottenham Hotspur FC 2 - 0 Coventry City FC",
            '["0.1", "0.9"]',
            bid: 0.08,
            ask: 0.12,
            spread: 0.04),
        exactScoreMarket(
            6,
            "Exact Score: Tottenham Hotspur FC 0 - 3 Coventry City FC?",
            "Tottenham Hotspur FC 0 - 3 Coventry City FC",
            '["0.065", "0.935"]',
            ask: 0.13,
            spread: 0.13),
        exactScoreMarket(
            7,
            "Exact Score: Tottenham Hotspur FC 1 - 2 Coventry City FC?",
            "Tottenham Hotspur FC 1 - 2 Coventry City FC",
            '["0.33", "0.67"]',
            ask: 0.66,
            spread: 0.66),
        exactScoreMarket(
            8,
            "Exact Score: Tottenham Hotspur FC 2 - 1 Coventry City FC?",
            "Tottenham Hotspur FC 2 - 1 Coventry City FC",
            '["0.095", "0.905"]',
            bid: 0.07,
            ask: 0.12,
            spread: 0.05),
        exactScoreMarket(
            9,
            "Exact Score: Tottenham Hotspur FC 3 - 0 Coventry City FC?",
            "Tottenham Hotspur FC 3 - 0 Coventry City FC",
            '["0.065", "0.935"]',
            bid: 0.04,
            ask: 0.09,
            spread: 0.05),
        exactScoreMarket(
            10,
            "Exact Score: Tottenham Hotspur FC 0 - 4 Coventry City FC?",
            "Tottenham Hotspur FC 0 - 4 Coventry City FC",
            '["0.36", "0.64"]',
            ask: 0.72,
            spread: 0.72),
        exactScoreMarket(
            11,
            "Exact Score: Tottenham Hotspur FC 1 - 3 Coventry City FC?",
            "Tottenham Hotspur FC 1 - 3 Coventry City FC",
            '["0.065", "0.935"]',
            ask: 0.13,
            spread: 0.13),
        exactScoreMarket(
            12,
            "Exact Score: Tottenham Hotspur FC 2 - 2 Coventry City FC?",
            "Tottenham Hotspur FC 2 - 2 Coventry City FC",
            '["0.0645", "0.9355"]',
            ask: 0.129,
            spread: 0.129),
        exactScoreMarket(
            13,
            "Exact Score: Tottenham Hotspur FC 3 - 1 Coventry City FC?",
            "Tottenham Hotspur FC 3 - 1 Coventry City FC",
            '["0.065", "0.935"]',
            bid: 0.04,
            ask: 0.09,
            spread: 0.05),
        exactScoreMarket(
            14,
            "Exact Score: Tottenham Hotspur FC 4 - 0 Coventry City FC?",
            "Tottenham Hotspur FC 4 - 0 Coventry City FC",
            '["0.365", "0.635"]',
            ask: 0.73,
            spread: 0.73),
        exactScoreMarket(
            15,
            "Exact Score: Tottenham Hotspur FC 0 - 5 Coventry City FC?",
            "Tottenham Hotspur FC 0 - 5 Coventry City FC",
            '["0.37", "0.63"]',
            ask: 0.74,
            spread: 0.74),
        exactScoreMarket(
            16,
            "Exact Score: Tottenham Hotspur FC 1 - 4 Coventry City FC?",
            "Tottenham Hotspur FC 1 - 4 Coventry City FC",
            '["0.335", "0.665"]',
            ask: 0.67,
            spread: 0.67),
        exactScoreMarket(
            17,
            "Exact Score: Tottenham Hotspur FC 2 - 3 Coventry City FC?",
            "Tottenham Hotspur FC 2 - 3 Coventry City FC",
            '["0.065", "0.935"]',
            ask: 0.13,
            spread: 0.13),
        exactScoreMarket(
            18,
            "Exact Score: Tottenham Hotspur FC 3 - 2 Coventry City FC?",
            "Tottenham Hotspur FC 3 - 2 Coventry City FC",
            '["0.33", "0.67"]',
            ask: 0.66,
            spread: 0.66),
        exactScoreMarket(
            19,
            "Exact Score: Tottenham Hotspur FC 4 - 1 Coventry City FC?",
            "Tottenham Hotspur FC 4 - 1 Coventry City FC",
            '["0.37", "0.63"]',
            ask: 0.74,
            spread: 0.74),
        exactScoreMarket(
            20,
            "Exact Score: Tottenham Hotspur FC 5 - 0 Coventry City FC?",
            "Tottenham Hotspur FC 5 - 0 Coventry City FC",
            '["0.365", "0.635"]',
            ask: 0.73,
            spread: 0.73),
        exactScoreMarket(
            21,
            "Exact Score: Tottenham Hotspur FC 1 - 5 Coventry City FC?",
            "Tottenham Hotspur FC 1 - 5 Coventry City FC",
            '["0.37", "0.63"]',
            ask: 0.74,
            spread: 0.74),
        exactScoreMarket(
            22,
            "Exact Score: Tottenham Hotspur FC 2 - 4 Coventry City FC?",
            "Tottenham Hotspur FC 2 - 4 Coventry City FC",
            '["0.065", "0.935"]',
            ask: 0.13,
            spread: 0.13),
        exactScoreMarket(
            23,
            "Exact Score: Tottenham Hotspur FC 3 - 3 Coventry City FC?",
            "Tottenham Hotspur FC 3 - 3 Coventry City FC",
            '["0.065", "0.935"]',
            ask: 0.13,
            spread: 0.13),
        exactScoreMarket(
            24,
            "Exact Score: Tottenham Hotspur FC 4 - 2 Coventry City FC?",
            "Tottenham Hotspur FC 4 - 2 Coventry City FC",
            '["0.37", "0.63"]',
            ask: 0.74,
            spread: 0.74),
        exactScoreMarket(
            25,
            "Exact Score: Tottenham Hotspur FC 5 - 1 Coventry City FC?",
            "Tottenham Hotspur FC 5 - 1 Coventry City FC",
            '["0.375", "0.625"]',
            ask: 0.75,
            spread: 0.75),
        exactScoreMarket(
            26,
            "Exact Score: Tottenham Hotspur FC 2 - 5 Coventry City FC?",
            "Tottenham Hotspur FC 2 - 5 Coventry City FC",
            '["0.04", "0.96"]',
            ask: 0.08,
            spread: 0.08),
        exactScoreMarket(
            27,
            "Exact Score: Tottenham Hotspur FC 3 - 4 Coventry City FC?",
            "Tottenham Hotspur FC 3 - 4 Coventry City FC",
            '["0.37", "0.63"]',
            ask: 0.74,
            spread: 0.74),
        exactScoreMarket(
            28,
            "Exact Score: Tottenham Hotspur FC 4 - 3 Coventry City FC?",
            "Tottenham Hotspur FC 4 - 3 Coventry City FC",
            '["0.34", "0.66"]',
            ask: 0.68,
            spread: 0.68),
        exactScoreMarket(
            29,
            "Exact Score: Tottenham Hotspur FC 5 - 2 Coventry City FC?",
            "Tottenham Hotspur FC 5 - 2 Coventry City FC",
            '["0.31", "0.69"]',
            ask: 0.62,
            spread: 0.62),
        exactScoreMarket(
            30,
            "Exact Score: Tottenham Hotspur FC 3 - 5 Coventry City FC?",
            "Tottenham Hotspur FC 3 - 5 Coventry City FC",
            '["0.35", "0.65"]',
            ask: 0.7,
            spread: 0.7),
        exactScoreMarket(
            31,
            "Exact Score: Tottenham Hotspur FC 4 - 4 Coventry City FC?",
            "Tottenham Hotspur FC 4 - 4 Coventry City FC",
            '["0.05", "0.95"]',
            ask: 0.1,
            spread: 0.1),
        exactScoreMarket(
            32,
            "Exact Score: Tottenham Hotspur FC 5 - 3 Coventry City FC?",
            "Tottenham Hotspur FC 5 - 3 Coventry City FC",
            '["0.325", "0.675"]',
            ask: 0.65,
            spread: 0.65),
        exactScoreMarket(
            33,
            "Exact Score: Tottenham Hotspur FC 4 - 5 Coventry City FC?",
            "Tottenham Hotspur FC 4 - 5 Coventry City FC",
            '["0.375", "0.625"]',
            ask: 0.75,
            spread: 0.75),
        exactScoreMarket(
            34,
            "Exact Score: Tottenham Hotspur FC 5 - 4 Coventry City FC?",
            "Tottenham Hotspur FC 5 - 4 Coventry City FC",
            '["0.36", "0.64"]',
            ask: 0.72,
            spread: 0.72),
        exactScoreMarket(
            35,
            "Exact Score: Tottenham Hotspur FC 5 - 5 Coventry City FC?",
            "Tottenham Hotspur FC 5 - 5 Coventry City FC",
            '["0.05", "0.95"]',
            ask: 0.1,
            spread: 0.1),
        exactScoreMarket(36, "Exact Score: Any Other Score?", "Any Other Score",
            '["0.375", "0.625"]',
            ask: 0.75, spread: 0.75, last: 0.01),
      ],
    };
